### ISSUE TITLE
My Apologies

### ISSUE THREAD

**Issue by I-A-C** [I-A-C/script.module.lambdascrapers#12]
I'm sorry for not being more vocal here.  I am pretty new to Github and I'm learning as I go along.

I know things are confusing right now with 3 different repos and what not.  Since creating the ExodusReduxRepo, I've been doing all new development in that repo and pretty much abandoned the older one.  I know that's bad form and want to get that fixed.

After several attempts, I finally got the ExodusReduxRepo setup properly on 0.0.4.  I just don't want to mess things up and invoke the wrath of reddit.

**Comment by turtlestv** [comment]
No problem we all have been there. We are here to help. My recommendation is to use the desktop application download both exodusredux and Exodus repo. Then to make it simple move all redux folder except the repo folder then compare both repos and merge them. Then update repo for the actual repo. Then move folder back into exodusredux and commit the changes to each. The exodusredux should remain untouched and the repo will be updated with all the commits. 

Then once you confirm all it working remove the repo folder from exodusredux repo and your set. 

You will have to add the exodusredux addon to the main repo. 

Letter me know if this makes sense or work like to see an example. 

Thanks!!

**Comment by I-A-C** [comment]
I work on an ubuntu setup.. so it's either command line or website.  I've made some changes as you've suggested. 

If I use  https://github.com/I-A-C/script.module.lambdascrapers/ for just LambdaScrapers should I keep it in the script.module.lambdascrapers folder or exposed like it is now?

**Comment by turtlestv** [comment]
I see... So make a make a repo named "LambdaScrapers"
move script.module.lambdascrapers folder into LambdaScrapers
merge the latest commits into it.
Done, now you have a dedicated repo outside of ExodusReduxRepo named "LambdaScrapers"

Now make another repo Repository "Lambda Repo"
move your current repository.lambdascrapers folder into it
Done, now you have a dedicated repo outside of Lambda Repo (for the updates)

Now delete all other repos EXCEPT **ExodusReduxRepo**

Now you have 3 repos "LambdaScrapers", "ExodusReduxRepo" and "Lambda Repo"

Now you need to update the repository.lambdascrapers xml for the all to sync up. 

hope this helps..

**Comment by turtlestv** [comment]
Based on what you have setup as on 10/19/18 @7AM PST, I went ahead and made a structure for you. 

https://drive.google.com/open?id=1jbKHY0XgCctI6ybzGyv2Wexo37yupOGo

This will give you the visual setup.

What I did was:
ExodusReduxRepo - removed "repository.exodusredux",  "script.module.lambdascrapers" and "zips" folders
They are in the zips folder

I-A-C-Repo - removed "zips" folder 
They are in the zips folder

LambdaScrapers - removed "zips/script.module.lambdascrapers"
They are in the zips folder

Added zip folder for all compressed files. Your repo now points to this folder for all files. 
**the repo in this folder is the only repo anyone needs for ExodusReduxRepo & LambdaScrapers.**

Here why this is a good structure:
So now when there is a commit to ExodusReduxRepo you just need to update the addon.xml version, zip it and place in zip folder. Kodi will check for updates and update automatically just EodusReduxRepo. The same goes for LambdaScrapers, when a there is a commit added you change the addon.xml zip it place in the zips folder and Kodi will update the LambdaScrapers module automatically.

The repo shouldn't need to be changed unless you add to it. Like if you wanted to remove Jsergios repo then you would have to update the addon.xml, create a addons.xml and addons.xml.md5 files. 

Also I dont see a need for "I-A-C.github.io" I would delete it.

Deciding on what you want to do you can use all these and update your git, You can delete everything and use these (back up first), use web browser and go one by one. 

I hope this helps.

**Comment by doko-desuka** [comment]
Hi. Based on what you have so far (Oct 19 16:36 UCT) and what @turtlestv suggested:
- Remember that people installed the repository.exodusredux add-on and it will look into https:\//raw.githubusercontent.com/I-A-C/ExodusReduxRepo/master/zips/ for the addons.xml, addons.xml.md5 and the add-on zip folders. Maybe you can [update the datadir folder](https://github.com/I-A-C/ExodusReduxRepo/blob/master/zips/repository.exodusredux/addon.xml#L7) in the addon.xml of repository.exodusredux to the new location, but still keep this ExodusReduxRepo/zips/ folder as legacy for a month or two for people that didn't update yet.
- The Github Pages repo (I-A-C.github.io) will be useful to people that like to install things with the "file source" way in Kodi. For those that don't like that, there's the zip archives to download as well, so it's different options.
- To keep things organized and to help you not make mistakes while comitting, it's better to have 1 repo for all the zips of your add-ons (including the repository add-on), and then one repo for each add-on source code. For naming and folder structure I like to use JSergio123's style: https://github.com/jsergio123, where each add-on repo has the direct file structure in it (less folders to worry about), but you should use any structure that makes sense to you since you're the one that'll use it.

**Comment by turtlestv** [comment]
Point/suggestion well noted and agreed. The community benefit is much greater that way.

Thanks

**Comment by SerpentDrago** [comment]
ohhh my its a mess right now .. you guys just had to go say something haha .

**Comment by turtlestv** [comment]
HAHAHAH!!!!! Looks much better now and contributing will be better for all. I'm glad they are getting it cleaned up. 

We will stay quite for a bit.........

GO DODGERS!!!!

**Comment by doko-desuka** [comment]
I don't think the loose addon.xml is read by Kodi.
It only checks the addons.xml.md5 for changes to know if the addons.xml needs to be redownloaded.  
Inside the updated addons.xml there should be new repository add-on entry with the updated datadir path. But just for safety you should update all copies of repository.exodusredux.zip with an addon.xml that points to the new, correct datadir path.

**Comment by doko-desuka** [comment]
PS: things are looking good in your repos! It takes one click to go into the add-on source, it's more transparent and accessible. Great job.

**Comment by SerpentDrago** [comment]
I think its more confusing now ! which one is the Kodi repo now ? zips ? 

and now i'll have to maintain forks of each part of the addons . and do pulls each time for each one to keep in date .. 

whatever you guys seem to think this is better .

**Comment by turtlestv** [comment]
I suggest waiting till he is complete with the reorg. Nothing has changed as far as addon/modules/etc. When its all done the repo will be updated and we can go from there. 
@I-A-C things look much better, good job!
@doko-desuka transparent is the ultimate way this works, great tips and suggestions!!!

**Comment by jewbmx** [comment]
Im not sure whats goin on lol but if we are designing I-A-C's account id wipe it all lol and go

_script.module.lambdascrapers
---everything Lambda
---Lambda Repo

_ExodusReduxRepo
---All addon files
---Repo addon

_I-A-C.github.io

**Comment by turtlestv** [comment]
@jewbmx lol late to the party... He has redone/reorg it. Its good how it is now. Once the repo is updated all is good and updates can begin again. 

@I-A-C  I suggest you post on reddit so that everyone knows you are reorganizing the git. Once updated clean all reddit posts and update with a master post.

**Comment by doko-desuka** [comment]
At the risk of sounding like a whiney bitch, I should offer apologies too... if I had been any more patient I would've noticed that your repos could also follow [the structure used by nixgates for Incursion](https://github.com/nixgates/Incursion), with just one master repository. Something like this:

> ### Repository ExodusRedux  
>> **Lambda Scrapers** (a folder)  
>>> _README.md_ (explaining what's Lambda Scrapers)  
>>> _script.module.lambdascrapers_  
>
>> **Exodus Redux** (another folder)  
>>> _README.md_ (explaining what's Exodus Redux)  
>>> _plugin.video.exodusredux_
>>> _script.exodusredux.metadata_
>>> _script.exodusredux.artwork_

This is also a completely valid structure. It's one repository ("Repository ExodusRedux") for people to send their bug reports and pull-requests. It's probably more organized than what I suggested on my earlier posts.

**Comment by I-A-C** [comment]
Damn you!! :) 
Glad I got those updates out before I saw this.

My main problem before was that I had the zips inside the ExodusReduxRepo and not it's own repository.  That part seem's to be straightened out now.

Now you gonna make be rethink things.  Good thing I left the ExodusReduRepo relatively intact.

Renaming repository  **ExodusReduxRepo** to **Exodus Redux** (folder) and repository **script.module.lambdascrapers** to back to **Lambda Scrapers** (folder) is pretty straight forward.

Creating one master repository **Repository ExodusRedux** and moving the 3 folders (4 including the github.io folder) under this master repository is tricky.

I can create the structure and commit everything as new.  However, I'm not sure how to do this AND maintain history.

**Comment by host505** [comment]
^^ No, I think it's much better the way it is now, because:
- If I want to submit a pr for eg lambdascrapers I don't have to fork the whole contents of the repo
- Separate repositories act as development branches, which are easier for testers to test changes. Just download the zip for said module from it's respective repository by clicking "Clone or download -> Download zip". And of course easier for the maintainer to upload test versions.

**Comment by doko-desuka** [comment]
Oh cool, I'd stick with whatever is easier to use.
