### ISSUE TITLE
LambdaScrapers -> Seren package generator

### ISSUE THREAD

**Issue by ghost** [I-A-C/script.module.lambdascrapers#48]
https://github.com/NOT-doko-desuka/temp/blob/master/GenerateLambdaSeren.py

Untested, WIP.  
To be used with https://github.com/nixgates/plugin.video.Seren

References:
- https://github.com/nixgates/plugin.video.Seren/blob/master/resources/lib/modules/providerInstaller.py
- https://github.com/NOT-doko-desuka/temp/blob/master/providers/__init__.py

**Comment by jewbmx** [comment]
Im not sure whats up with all that lol but i think the person was passing off their work to you and im guessing it was just whats here... (found in their reddit post) https://pastebin.com/raw/sge6VtcE

**Comment by jewbmx** [comment]
I assume it had to do with making nix's new addon and LS compatible. But if yall make those packages id think of some nice ways to split em up into different groups or something so its not a huge file and to try and prevent future dupes issues.

**Comment by doko-desuka** [comment]
From what they're saying in that reddit post, they don't think it can be done right now, not without some modifications to nix's Seren.

**Comment by jewbmx** [comment]
Just turn on your RD and enable that dbird only setting and put those scrapers in a folder somewhere to edit and use for nixgates, I assume that could maybe work. Think i seen nixgates say somewhere that it will be for free users too sooner or later

**Comment by rrosajp** [comment]
@jewbmx 
@doko-desuka 
they added hear [https://github.com/reddit-reaper/ScraperPackages](url)
but some how need some more setting in seren.

**Comment by jewbmx** [comment]
Thanks rosa didnt know lol.

Only took a quick glance for now but it looks like they are doing a full pile of both types and might not be doing as much of a rewrite as i was thinking.

I figured we could take the scrapers that give RD results and change them to RD only then research the addon and current working package to rewrite the scrapers to match his addon.

Also spotted some scrapers the other day somewhere from an older addon that looked like they would work in nix's addon with very few changes but as always ive forgotten to make a note for my baked brain lol

**Comment by jewbmx** [comment]
I dont use any premo accounts so i probably wont be helping with this kinda stuff honestly unless asked to, but think domain updates are all id be useful for lmao plus im on a s7 phone so quite limited in ways.

**Comment by SerpentDrago** [comment]
I dont' see how getting lambdascrapers to work with seren is "out of scope" 

The whole point of this project is to provide a central place for scrapers . if it can be made to work with multiple types of addons the better . 

If any dev needs a  free PM account for development , hit Reaper/Cody up on Reddit . or reach out to me .

**Comment by doko-desuka** [comment]
> I dont' see how getting lambdascrapers to work with seren is "out of scope"

Hi. I didn't say getting LS to work with Seren is out of scope, I said that _this Issue_ is out of scope since the files in the OP seem to be gone (their whole account is gone too).  
But I still think that Seren should focus on premium hosters, and ExodusRedux or 13Clowns etc. should focus on free-hosters. I think it's better to have two simple add-ons working fast and well at specific things, than one single add-on trying to do it all, more room for optimization.

**Comment by 13Clowns** [comment]
We are working on adding upnext to 13clowns and plan on staying with ls for both free and Rd.  Honestly have had much time to look at seven. This weekend we will though.

Agree having stable fast addons is much better for the end-user.

**Comment by SerpentDrago** [comment]
I guess i'll just keep plugging away at my metaliq fork , so i can have a easy way to play something that doesnt' find sources in one or the other :) 

Sounds good guys

**Comment by host505** [comment]
I don't see how this project should be bothered to port Ls to work with seren (or any non-exodus based add-on). It's a module for exodus-based add-ons. I'm not the one saying that, readme does.
Of course anyone can do it (and already does), it's foss.
But whoever maintains the Ls seren port should be more careful about double-scraping, because right now a4k & Ls have some common scrapers (rlsbb & 2ddl), that means if a user enables both packages double scraping occurs on these sites (well 2ddl is currently broken on a4k package so doesn't occur on that one).

**Comment by jewbmx** [comment]
Im so lost lmao, doesnt reddit_reaper already have a LS package done? Why not leave that to the people that work with seren. I feel like its the same as asking to blend this project with the UniversalScrapers project lol
