### ISSUE TITLE
2DDL is has now changed to Invictus

### ISSUE THREAD

**Issue by JFG90** [I-A-C/script.module.lambdascrapers#54]
Hi guys just seen a post from themselves that 2DDL is now Invictus, with a new website it seems http://invictus.ws

Is this something that needs to be edited in lambdascrapers? Just wanted to give you a heads up!

**Comment by jewbmx** [comment]
Pretty sure someone made the invictus scraper already, dont remember the full addon name but my buddy said its something like Temp**. Can also check out eggmans addons and see if hes got it

**Comment by drchud** [comment]
> 
> 
> Pretty sure someone made the invictus scraper already, dont remember the full addon name but my buddy said its something like Temp**. Can also check out eggmans addons and see if hes got it

@jewbmx You are a fucking poser lol. Just like eggman......u can't code, just a copy and paster lol. Steal all scrapers cause u never coded python in ur life. Tell the truth bitch. Oh wait even u said fuck darewatch about a month back cause u couldn't fix the cfscrape. But wait now since someone fix the major part even thought he left off the resolver......so now u include it in your addon lol. Hey u said fuck that site cause the links suck and i dont like it. Two faced lying bitch!
 Apparently u haven't learned shit from tantrum. You walk around like u know shit, fact is u don't. Good luck fag.

**Comment by drchud** [comment]
@JFG90 Stop posting stuff in here as u can see this project is finished, done, and everyone was scammed lol

**Comment by SerpentDrago** [comment]
NO one here is under any illusions of claiming any work as themselfs , go home , this is Piracy you idiot , Its all open code . 

Long live Kodi ! lol

**Comment by drchud** [comment]
I had the forsight to see this lambda scraper shit wouldn't last long. Odds were stacked against u guys the whole fucking time. The major key component to running an exodus style fork and or a set of scrapers IS TO KNOW HOW TO FIX THEM AND CODE MORE WHEN NEEDED! 

Didn't whats his face....oh yeah nixgates even say its the heart and soul of this style addon??
This just shows how stupid this project really was. I'm mean sure....you did fool a lot of people, newbs at a4k, youtubes etc. Pretty sad. So when are u going to start being honest with all the fans at a4k???
Or do more troll accounts need to be created to spread the truth?

**Comment by drchud** [comment]
Just so people can understand here is a quote from IAC or I_am_terrabull (On a4k)

> To be honest I have my own curated list with my own scraper modifications. However, I do plan to eventually get around to consolidating these publicly sourced scrapers.

Now mind u this was 3 to 4 months ago lol
